# Generated by Django 6.0.4 on 2026-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='message',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
